### ISSUE TITLE
ADA Layout

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#10]
Innovation Center will require that there is an ADA layout where any fields which require interaction are constrained to the lower half of the screen (aka below 48").

**Comment by tman0** [comment]
I almost feel like we could get rid of the register screen entirely except when ACaPS is down, IIRC that's the only user-facing interaction which would fall under that. Would admin tools fall under this as well, given that they aren't user-facing?

**Comment by pkarnia** [comment]
Confirm that all required user screen interactions are below 48". If so close issue.
