### ISSUE TITLE
Deauth Button

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#15]
Add button to admin tools for developers and Lab Manager to deauth a kiosk without an address bar.

**Comment by tellowkrinkle** [comment]
It looks like you can deauthorize by selecting `Manage Locations` → \<Name of Location\> → Scroll to Bottom → Tap `X` button next to kiosk

**Comment by tman0** [comment]
Patrick wanted an easier method to do it on the main page of the Admin UI
