### ISSUE TITLE
Some routes violate HTTP / RFC7231 standards

### ISSUE THREAD

**Issue by nkaminski** [iit-ideashop/check-in-app#17]
The HTTP 1.1 standard, RFC7231, states in section 4 that the GET HTTP method is defined as a "safe" method. This means that the mere action of making a GET request **must not persistently change the state** of the application.

However, I have noticed that there are a handful of routes that do cause state changes (such as admin logout and kiosk deauth) in response to GET requests. This may result in non-deterministic issues with recent releases of Chrome which prefetch specific page content which the browser predicts that the user will access next.

Therefore, I strongly advise using the POST or DELETE method for these actions, which are defined as "unsafe" meaning that browsers expect such to make changes and in the case of POST only, that such changes may not be idempotent.

**Comment by tman0** [comment]
Good catch. If #16 only happens on a user's first check-in this could potentially be the cause, as check in is typically performed via JavaScript redirect.
