### ISSUE TITLE
Training.completed() Errors

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#46]
https://github.com/iit-ideashop/check-in-app/blob/16db9a0b360203b8d434fba7094fd4f20154782d/checkIn/model.py#L95
Should we be screening for invalidation dates in the completed function? I can't really think of any reason we would want to return an invalidated Training as completed for it might be better to include it here in case someone forgets to filter their query by `invalidation_date is not None`.

https://github.com/iit-ideashop/check-in-app/blob/16db9a0b360203b8d434fba7094fd4f20154782d/checkIn/model.py#L97
This would not parse correctly. Should consider `json.loads()` instead of `list()` typecast. This should allow us to store the list object as `varchar = "[1,2,3]"` for example.

**Comment by AlirpJ** [comment]
List was changed to json.loads() but not here
https://github.com/iit-ideashop/check-in-app/blob/452f790bb1bc361563c5ef46146255416a11fcf7/checkIn/model.py#L105

Was that an appropriate change, or should this be changed as well?

**Comment by pkarnia** [comment]
You can leave as list type for https://github.com/iit-ideashop/check-in-app/blob/452f790bb1bc361563c5ef46146255416a11fcf7/checkIn/model.py#L105 since we won't necessarily need to use this function to dump the list into the DB.
