### ISSUE TITLE
Improper use of class functions. Causes breakage during card tap flow

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#53]
What was the original purpose of this code?
It currently causes errors during a card tap event.
If commented out then card_tap flow proceeds as expected.
Is this deprecated now?

https://github.com/iit-ideashop/check-in-app/blob/bc2af874a5496af7295d29fefc6f07bcaccf41c0/checkIn/socketio_handlers/v1.py#L167-L176
https://github.com/iit-ideashop/check-in-app/blob/bc2af874a5496af7295d29fefc6f07bcaccf41c0/checkIn/socketio_handlers/v1.py#L197-L206 (also is this second block an unintended duplicate)

From what I can tell it could be better rewritten into the get missing trainings function. https://github.com/iit-ideashop/check-in-app/blob/bc2af874a5496af7295d29fefc6f07bcaccf41c0/checkIn/model.py#L237

**Comment by AlirpJ** [comment]
I believe the second block is an unintended duplicate, I must have missed that. 

Do you mean that the code block can utilize get_missing_trainings?

^We'll talk at the meeting

**Comment by pkarnia** [comment]
Fixed with a5fddac
