### ISSUE TITLE
Update button text for better context

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#57]
update the button text to have better context of what is done.
![Screenshot 2021-08-05 145904](https://user-images.githubusercontent.com/6912671/128414449-099d0dae-e8e1-4ffb-a657-34b1c867f9c8.png)

**Comment by AlirpJ** [comment]
Made a PR with the change https://github.com/iit-ideashop/check-in-app/pull/60

However, there are some other changes showing up for this branch, and I don't know why? I never added these files to the branch, but I remember making some of these changes when my check-in-app config was acting weird or the app wasn't running

**Comment by AlirpJ** [comment]
New PR https://github.com/iit-ideashop/check-in-app/pull/61
