### ISSUE TITLE
Javascript to stop looping audio not properly triggering

### ISSUE THREAD

**Issue by tman0** [iit-ideashop/check-in-app#7]

**Comment by tellowkrinkle** [comment]
It seemed to be working earlier...
It's not the whole page though.  Do you think that we should make it trigger on the whole page (it's currently on the element that contains the main set of buttons)

**Comment by tman0** [comment]
Yeah it should trigger no matter where you tap

**Comment by tellowkrinkle** [comment]
OK I can change that

**Comment by tman0** [comment]
Fix in 61f7f16

**Comment by tman0** [comment]
#8
